### ISSUE TITLE
Is not possible to hide the html and kist callit with a button?

### ISSUE THREAD

**Issue by R4k4210** [francescochiapello/react-pdf-print#3]
I have the case of just click a button, and print the HTML. But if a i hide or display none the HTML, pdf print blank page.
Thanks!

**Comment by umbertoghio** [comment]
Hi, 
this package leverages the browser's render of the HTML, so it needs to be displayed.
An alternative is to use puppeteer on a server to render the react HTML and print it directly

**Comment by R4k4210** [comment]
Thank for you answer! So this is not an issue. Closed.
